# https://console.developers.google.com/apis/credentials/oauthclient
# 1. Application type : Web application
# 2. Name : Your project name
# 3. Authorized JS origins : This is the origin URI of the client application
# ex) http://localhost:8080
# 4. Authorized redirect URIs : 3 + "/login/oauth2/code/google"
# ex) http://localhost:8080/login/oauth2/code/google
# 5. Create
# 6. Check client-id
# 7. Check client-secret

# https://github.com/settings/developers
# 8. OAuth2 click
# 9. Check client-id
# 10. Check client-secret

# https://developers.facebook.com/apps/
# 11. New App(Personal Security Authentication) - Setting
# 12. Check client-id
# 13. Check client-secret
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: # 6
            clientSecret: # 7
            redirectUriTemplate: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
          github:
            clientId: # 9
            clientSecret: # 10
            redirectUriTemplate: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - user:email
              - read:user
          facebook:
            clientId: # 12
            clientSecret: # 13
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile